// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SingularFlow.Infrastructure.Persistence;

#nullable disable

namespace SingularFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SingularFlowDbContext))]
    partial class SingularFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SingularFlow.Infrastructure.Persistence.Entities.SimulationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("ConcentrationExponent")
                        .HasColumnType("double precision")
                        .HasColumnName("concentration_exponent");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("EndTime")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer")
                        .HasColumnName("sample_count");

                    b.Property<string>("SamplingMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sampling_mode");

                    b.Property<double>("SingularTime")
                        .HasColumnType("double precision")
                        .HasColumnName("singular_time");

                    b.Property<double>("StartTime")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_simulations");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_simulations_created_at_utc");

                    b.ToTable("simulations", null, t =>
                        {
                            t.HasCheckConstraint("ck_simulations_concentration_exponent", "\"concentration_exponent\" > 0 AND \"concentration_exponent\" < 0.01");

                            t.HasCheckConstraint("ck_simulations_end_time", "\"end_time\" > \"start_time\"");

                            t.HasCheckConstraint("ck_simulations_sample_count", "\"sample_count\" >= 2 AND \"sample_count\" <= 100000");

                            t.HasCheckConstraint("ck_simulations_singular_time", "\"singular_time\" > \"end_time\"");

                            t.HasCheckConstraint("ck_simulations_start_time", "\"start_time\" >= 0");
                        });
                });

            modelBuilder.Entity("SingularFlow.Infrastructure.Persistence.Entities.SimulationStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AngularVelocityScale")
                        .HasColumnType("double precision")
                        .HasColumnName("angular_velocity_scale");

                    b.Property<double>("AxialLength")
                        .HasColumnType("double precision")
                        .HasColumnName("axial_length");

                    b.Property<double>("CoreEnergyScale")
                        .HasColumnType("double precision")
                        .HasColumnName("core_energy_scale");

                    b.Property<double>("CoreVolumeScale")
                        .HasColumnType("double precision")
                        .HasColumnName("core_volume_scale");

                    b.Property<double>("RadialLength")
                        .HasColumnType("double precision")
                        .HasColumnName("radial_length");

                    b.Property<double>("RadialVelocityScale")
                        .HasColumnType("double precision")
                        .HasColumnName("radial_velocity_scale");

                    b.Property<double>("RemainingTime")
                        .HasColumnType("double precision")
                        .HasColumnName("remaining_time");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("uuid")
                        .HasColumnName("simulation_id");

                    b.Property<double>("Time")
                        .HasColumnType("double precision")
                        .HasColumnName("time");

                    b.HasKey("Id")
                        .HasName("pk_simulation_states");

                    b.HasIndex("SimulationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_simulation_states_simulation_id_sequence");

                    b.ToTable("simulation_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_simulation_states_sequence", "\"sequence\" >= 0");
                        });
                });

            modelBuilder.Entity("SingularFlow.Infrastructure.Persistence.Entities.SimulationStateEntity", b =>
                {
                    b.HasOne("SingularFlow.Infrastructure.Persistence.Entities.SimulationEntity", "Simulation")
                        .WithMany("States")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_simulation_states_simulations_simulation_id");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("SingularFlow.Infrastructure.Persistence.Entities.SimulationEntity", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
